# permissions for end users to edit githubsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: githubsecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: github-action-secret-operator
    app.kubernetes.io/part-of: github-action-secret-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubsecret-editor-role
rules:
- apiGroups:
  - secret.fr123k.uk
  resources:
  - githubsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.fr123k.uk
  resources:
  - githubsecrets/status
  verbs:
  - get
