---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - secret.fr123k.uk
  resources:
  - githubsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret.fr123k.uk
  resources:
  - githubsecrets/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secret.fr123k.uk
  resources:
  - githubsecrets/status
  verbs:
  - get
  - patch
  - update
