apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: github-action-secret-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GithubSecret is the Schema for the githubsecrets API
      displayName: Github Secret
      kind: GithubSecret
      name: githubsecrets.secret.fr123k.uk
      version: v1alpha1
  description: The Github Action Secrets Operator manage the Github Action Secrets
    for Github Repositories by reading the secret values from Google Cloud Secret
    Manager and store them as Github Action Secrets in the configured repository.
  displayName: Github Action Secrets Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gha
  - secret
  - dependabot
  links:
  - name: Github Action Secret Operator
    url: https://github-action-secret-operator.domain
  maintainers:
  - email: frank.ittermann@yahoo.de
    name: frank
  maturity: alpha
  provider:
    name: gha-secret-operator
  version: 0.0.0
